// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wms/app/model/internal"
)

// CustomerOrders is the golang structure for table customer_orders.
type CustomerOrders internal.CustomerOrders

// Fill with you ideas below.