// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wms/app/model/internal"
)

// CustomerOrderAddresses is the golang structure for table customer_order_addresses.
type CustomerOrderAddresses internal.CustomerOrderAddresses

// Fill with you ideas below.