// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wms/app/model/internal"
)

// CustomerOrderProducts is the golang structure for table customer_order_products.
type CustomerOrderProducts internal.CustomerOrderProducts

// Fill with you ideas below.