// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wms/app/model/internal"
)

// ProductSkus is the golang structure for table product_skus.
type ProductSkus internal.ProductSkus

// Fill with you ideas below.