// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wms/app/model/internal"
)

// Stocks is the golang structure for table stocks.
type Stocks internal.Stocks

// Fill with you ideas below.