// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CustomerOrders is the golang structure for table customer_orders.
type CustomerOrders struct {
    Id            uint        `orm:"id,primary"      json:"id"`              //                                                             
    OrderId       string      `orm:"order_id"        json:"order_id"`        // 订单ID                                                      
    UserId        uint        `orm:"user_id"         json:"user_id"`         // 用户ID                                                      
    TotalNum      int         `orm:"total_num"       json:"total_num"`       // 购买的总数量                                                
    FinalPrice    float64     `orm:"final_price"     json:"final_price"`     // 成交价(支付金额)                                            
    PayChannel    string      `orm:"pay_channel"     json:"pay_channel"`     // 付款方式 1-余额支付 2-paypal支付 3-stripe支付               
    PayMethod     string      `orm:"pay_method"      json:"pay_method"`      //                                                             
    CurrencyCode  string      `orm:"currency_code"   json:"currency_code"`   //                                                             
    Abbreviation  string      `orm:"abbreviation"    json:"abbreviation"`    // 货币编码                                                    
    FromType      int         `orm:"from_type"       json:"from_type"`       // 单订来源，1：PC端，2：H5，3：小程序，4：IOS，5：android     
    Status        int         `orm:"status"          json:"status"`          // 订单状态 1-待付款 3-待发货 4-待收货 5-交易完成 6-交易取消   
    PickingId     int         `orm:"picking_id"      json:"picking_id"`      //                                                             
    UserLocalTime string      `orm:"user_local_time" json:"user_local_time"` // 用户本地时间                                                
    Language      string      `orm:"language"        json:"language"`        // 语言                                                        
    CreatedAt     *gtime.Time `orm:"created_at"      json:"created_at"`      // 创建时间                                                    
    PayAt         *gtime.Time `orm:"pay_at"          json:"pay_at"`          // 付款时间                                                    
    DeliveryAt    *gtime.Time `orm:"delivery_at"     json:"delivery_at"`     // 货发时间                                                    
    SignAt        *gtime.Time `orm:"sign_at"         json:"sign_at"`         // 签收时间                                                    
    AuditAt       *gtime.Time `orm:"audit_at"        json:"audit_at"`        // 审核时间                                                    
    CancelAt      *gtime.Time `orm:"cancel_at"       json:"cancel_at"`       //                                                             
    Note          string      `orm:"note"            json:"note"`            //                                                             
    StockStatus   int         `orm:"stock_status"    json:"stock_status"`    // 1:缺货；0：配送中 3库存等待 4已分配 5已生成拣货单 6已取消   
    DeletedAt     *gtime.Time `orm:"deleted_at"      json:"deleted_at"`      // 删除时间                                                    
    UpdatedAt     *gtime.Time `orm:"updated_at"      json:"updated_at"`      // 修改时间                                                    
    WmsStatus     int         `orm:"wms_status"      json:"wms_status"`      // 仓储订单状态1.待收货（生成拣货单） 2已出库（清点包裹完成）  
    MessageId     string      `orm:"message_id"      json:"message_id"`      //                                                             
}