// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CustomerOrderAddresses is the golang structure for table customer_order_addresses.
type CustomerOrderAddresses struct {
    Id             uint        `orm:"id,primary"     json:"id"`             //               
    OrderId        string      `orm:"order_id"       json:"order_id"`       //               
    Firstname      string      `orm:"firstname"      json:"firstname"`      // 姓            
    Lastname       string      `orm:"lastname"       json:"lastname"`       // 名            
    Country        string      `orm:"country"        json:"country"`        // 国家          
    CountryCode    string      `orm:"country_code"   json:"country_code"`   //               
    State          string      `orm:"state"          json:"state"`          // 州/省份/区域  
    City           string      `orm:"city"           json:"city"`           // 城市          
    Street         string      `orm:"street"         json:"street"`         // 详细地址      
    StreetNumber   string      `orm:"street_number"  json:"street_number"`  //               
    Suburb         string      `orm:"suburb"         json:"suburb"`         // apt/郊区地址  
    Zipcode        string      `orm:"zipcode"        json:"zipcode"`        // 邮政编码      
    Areacode       string      `orm:"areacode"       json:"areacode"`       // 区号          
    Phone          string      `orm:"phone"          json:"phone"`          // 电话          
    Email          string      `orm:"email"          json:"email"`          //               
    Identification string      `orm:"identification" json:"identification"` //               
    CreatedAt      *gtime.Time `orm:"created_at"     json:"created_at"`     //               
    DeletedAt      *gtime.Time `orm:"deleted_at"     json:"deleted_at"`     //               
    UpdatedAt      *gtime.Time `orm:"updated_at"     json:"updated_at"`     //               
    MessageId      string      `orm:"message_id"     json:"message_id"`     //               
}