// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Stocks is the golang structure for table stocks.
type Stocks struct {
    Id               int         `orm:"id,primary"         json:"id"`                 //                 
    ProductId        int         `orm:"product_id"         json:"product_id"`         //                 
    SkuId            int         `orm:"sku_id"             json:"sku_id"`             //                 
    LogicOccupyStock int         `orm:"logic_occupy_stock" json:"logic_occupy_stock"` // 逻辑占用库存    
    LogicRemainStock int         `orm:"logic_remain_stock" json:"logic_remain_stock"` // 逻辑剩余库存    
    PhysicsStock     int         `orm:"physics_stock"      json:"physics_stock"`      // 在架库存        
    PreJobStock      int         `orm:"pre_job_stock"      json:"pre_job_stock"`      // 预作业库存      
    StorageStock     int         `orm:"storage_stock"      json:"storage_stock"`      // 入库作业中库存  
    OutboundStock    int         `orm:"outbound_stock"     json:"outbound_stock"`     // 出库作业库存    
    SafeStock        int         `orm:"safe_stock"         json:"safe_stock"`         // 安全库存        
    NotReceivedStock int         `orm:"not_received_stock" json:"not_received_stock"` // 已推未到        
    BalanceStock     int         `orm:"balance_stock"      json:"balance_stock"`      // 结余量          
    LockStock        uint        `orm:"lock_stock"         json:"lock_stock"`         // 锁定库存        
    ChoiceNotShip    uint        `orm:"choice_not_ship"    json:"choice_not_ship"`    // 待发备货数      
    CreatedAt        *gtime.Time `orm:"created_at"         json:"created_at"`         //                 
    UpdatedAt        *gtime.Time `orm:"updated_at"         json:"updated_at"`         //                 
}