// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"wms/app/dao/internal"
)

// customerOrderAddressesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type customerOrderAddressesDao struct {
	*internal.CustomerOrderAddressesDao
}

var (
	// CustomerOrderAddresses is globally public accessible object for table customer_order_addresses operations.
	CustomerOrderAddresses = &customerOrderAddressesDao{
		internal.CustomerOrderAddresses,
	}
)

// Fill with you ideas below.