// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"wms/app/dao/internal"
)

// customerOrdersDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type customerOrdersDao struct {
	*internal.CustomerOrdersDao
}

var (
	// CustomerOrders is globally public accessible object for table customer_orders operations.
	CustomerOrders = &customerOrdersDao{
		internal.CustomerOrders,
	}
)

// Fill with you ideas below.