// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"wms/app/dao/internal"
)

// customerOrderProductsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type customerOrderProductsDao struct {
	*internal.CustomerOrderProductsDao
}

var (
	// CustomerOrderProducts is globally public accessible object for table customer_order_products operations.
	CustomerOrderProducts = &customerOrderProductsDao{
		internal.CustomerOrderProducts,
	}
)

// Fill with you ideas below.