// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"wms/app/dao/internal"
)

// productSkusDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type productSkusDao struct {
	*internal.ProductSkusDao
}

var (
	// ProductSkus is globally public accessible object for table product_skus operations.
	ProductSkus = &productSkusDao{
		internal.ProductSkus,
	}
)

// Fill with you ideas below.